version: '3.8'

services:
  test_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: knowledge_base_test_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Use a different port to avoid conflict with local db
    volumes:
      - test_db_data:/var/lib/postgresql/data

volumes:
  test_db_data:
